language: csharp
solution: "./FlittSDK.sln"
mono: latest
dotnet: 2.2.100
install:
    - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
    - travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./FlittSDK.sln
script:
    - msbuild ./FlittSDK.sln
    - dotnet vstest FlittSDKTest/bin/Debug/FlittSDKTest.dll